server:
  port: 81

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/acd_test?serverTimezone=UTC
      username: root
      password: root

  redis:
    host: localhost
    port: 6379
    client-type: jedis # \u4E0E lettuce \u662F\u4E24\u79CD\u4E0D\u540C\u7684\u5BA2\u6237\u7AEF\u6280\u672F\uFF0C\u9ED8\u8BA4\u662Flettuce\uFF0C\u65E0\u7EBF\u7A0B\u5B89\u5168\u95EE\u9898
    database: 0 # Redis数据库索引（默认为0）
    password:
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto # 采用自增形式，否则id随机
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #log日志打印
mybatis:
  type-aliases-package: netease.test.entity
  mapper-locations: classpath:resources/mapper/*.xml

logging:
  level:
    netease=debug:

