server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
      username: root
      password: root
mybatis-plus:
  global-config:
    db-config:
      id-type: auto # 解决数据库自增id不匹配问题，由于mp采用雪花算法分配id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mp打印日志致控制台
