
# \u5E94\u7528\u73AF\u5883
# \u516C\u5171\u914D\u7F6E\uFF0C\u4E00\u822C\u653E\u516C\u7528\u7684
spring:
  profiles:
    active: @profile.active@
    group:
      "dev": devDB,devMVC
      "pro": devDB,proMVC
#    active: pro


