server:
  port: 8083
country: china

#likes:
#  - game
#  - music

user1:
  name: zhangsan
  age: 18
#  - name: lisi
#    age: 20
baseDir: c:\win
tmpDir: ${baseDir}\okky
enterprise:
  name: itcast
  age: 16
  tel: 1313
  subject:
    - Java
    - 前端
# 创建类，用于封装下面的数据
# 由spring帮我们加载数据到对象中，一定要告诉spring加载这组信息
# 使用时从spring中直接获取信息使用
datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: root
